restaurant/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app.views import (IndexView, CreateUserView, ProfileUpdateView, MenuItemCreateView,
MenuItemListView, MenuItemUpdateView, MenuItemDetailView, MenuItemDeleteView,
OrderCreateView, OrderListView, OrderUpdateView)
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', IndexView.as_view(), name='index_view'),
    url(r'^create_user/$', CreateUserView.as_view(), name='create_user_view'),
    url(r'^accounts/profile/$', login_required(ProfileUpdateView.as_view()), name="profile_update_view"),
    url(r'^menu_item_create/$', login_required(MenuItemCreateView.as_view()), name='menu_item_create_view'),
    url(r'^menu_item_list/$', login_required(MenuItemListView.as_view()), name='menu_item_list_view'),
    url(r'^update_menu_item/(?P<pk>\d+)/$', login_required(MenuItemUpdateView.as_view()), name='menu_item_update_view'),
    url(r'^delete_menu_item/(?P<pk>\d+)/$', login_required(MenuItemDeleteView.as_view()), name='menu_item_delete_view'),
    url(r'^order_create/$', login_required(OrderCreateView.as_view()), name='order_create_view'),
    url(r'^order_list', login_required(OrderListView.as_view()), name='order_list_view'),
    url(r'^order_update/(?P<pk>\d+)/$', login_required(OrderUpdateView.as_view()), name='order_update_view'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save



# Create your models here.

class Position(models.Model):
    position = models.CharField(max_length=20)

    def __str__(self):
        return self.position

class Profile(models.Model):
    user = models.OneToOneField('auth.User')
    position = models.ForeignKey(Position, null=True, blank=True)

class Category(models.Model):
    category = models.CharField(max_length=50)

    def __str__(self):
        return self.category

class Menu(models.Model):
    user = models.ForeignKey('auth.User')
    item = models.CharField(max_length=50)
    description = models.TextField()
    category = models.ForeignKey(Category)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    photo = models.ImageField(upload_to="item_photos", null=True, blank=True)

    def __str__(self):
        return self.item

    @property
    def photo_url(self):
        if self.photo:
            return self.photo.url


class Order(models.Model):
    server = models.ForeignKey('auth.User')
    created = models.DateTimeField(auto_now_add=True)
    fulfilled = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

class Items(models.Model):
    order_id = models.ForeignKey(Order)
    item = models.ForeignKey(Menu, blank=True, null=True)
    quantity = models.PositiveSmallIntegerField(blank=True, null=True)
    notes = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return str(self.order_id)

@receiver(post_save, sender='auth.User')
def create_user_profile(**kwargs):
    created = kwargs.get("created")
    instance = kwargs.get("instance")
    if created:
        Profile.objects.create(user=instance)

app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DetailView, DeleteView
from django.contrib.auth.models import User
from app.models import Profile, Order, Menu, Items, Category
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from extra_views import InlineFormSet, CreateWithInlinesView, UpdateWithInlinesView
from extra_views.generic import GenericInlineFormSet
from decimal import *

# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

class CreateUserView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = "/login"

class ProfileUpdateView(UpdateView):
    model = Profile
    fields = ['position']
    success_url = reverse_lazy('profile_update_view')

    def get_object(self, queryset=None):
        return self.request.user.profile

class MenuItemCreateView(CreateView):
    model = Menu
    fields = ['item', 'description', 'category', 'price', 'photo']
    success_url = reverse_lazy('menu_item_list_view')

    def form_valid(self, form):
        item = form.save(commit=False)
        item.user = self.request.user
        return super().form_valid(form)

class MenuItemListView(ListView):
    model = Category
    template_name = 'app/menu_list.html'

    def get_queryset(self):
        category = Category.objects.all()
        return category


class MenuItemDetailView(DetailView):
    model = Menu

    def get_queryset(self, **kwargs):
        item_id = self.kwargs.get('pk')
        return Menu.objects.filter(id=item_id)


class MenuItemUpdateView(UpdateView):
    model = Menu
    fields = ['item', 'description', 'category', 'price', 'photo']
    success_url = reverse_lazy('menu_item_list_view')

    def get_queryset(self, **kwargs):
        item_id = self.kwargs.get('pk')
        return Menu.objects.filter(id=item_id)

class MenuItemDeleteView(DeleteView):
    success_url = reverse_lazy("menu_item_list_view")

    def get_queryset(self):
        return Menu.objects.all()

class ListItemCreateView(CreateView):
        pass

class ItemInlineView(InlineFormSet):
    model = Items
    fields = ['item', 'quantity', 'notes']


class OrderCreateView(CreateWithInlinesView):
    model = Order
    inlines = [ItemInlineView]
    fields = ['paid', 'fulfilled']

    def forms_valid(self, form, inlines):
        form = form.save(commit=False)
        form.server = self.request.user
        form.save()
        for formset in inlines:
            print(formset.instance)
            formset.save()
        return HttpResponseRedirect(reverse_lazy('profile_update_view'))

#django-extra-views https://github.com/AndrewIngram/django-extra-views/


class OrderListView(ListView):
    model = Order
    template_name = 'app/order_list.html'

    def get_queryset(self):
        if self.request.user.profile.position.id == 2:
            return Order.objects.filter(fulfilled=False).order_by('created')
        if self.request.user.profile.position.id == 1:
            return Order.objects.filter(paid=False).order_by('created')


class OrderUpdateView(UpdateWithInlinesView):
    model = Order
    fields = ['paid', 'fulfilled']
    template_name = 'app/order_update.html'
    success_url = reverse_lazy('order_list_view')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        context['order'] = Order.objects.get(id=pk)
        items = Items.objects.filter(order_id=pk)

        tax_rate = 0.08
        tax_rate_for_total = 1.08
        subtotal = 0
        tax_total = 0
        grand_total = 0


        for item in items:
            subtotal += (item.item.price * item.quantity)
            item_tax = round(Decimal(item.item.price * item.quantity) * Decimal(tax_rate),2)
            tax_total += item_tax
            item_total = round(Decimal(item.item.price * item.quantity) + Decimal(item_tax),2)
            grand_total += item_total

        context['items'] = items
        context['tax_rate'] = tax_rate
        context['tax_total'] = tax_total
        context['tax_rate_for_total'] = tax_rate_for_total
        context['subtotal'] = subtotal
        context['grand_total'] = grand_total
        return context

templates/app/menu_confirm_delete.html
{% extends "base.html" %}

{% block content %}
{% if user.profile.position.id = 3 %}
  <form class="" action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-danger" name="submit" value="Confirm Delete">
  </form>
{% else %}
<h3><em>You don't have permission to view this page.</em></h3>
{% endif %}
<br>
<a href="javascript:history.go(-1)"><em>Return to Previous Page</em></a>

{% endblock %}

templates/app/menu_form.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
{% if user.profile.position.id = 3 %}

<strong><h4>Create/Update Menu Item: </h4></strong><hr>

  <form class="" action="" method="post" enctype=multipart/form-data>
    {% csrf_token %}

    {{form|bootstrap}}

      <div class="form-group">
        {{form.errors}}
      </div>
      <button type="submit" class="btn btn-primary">Submit Menu Item</button>
      {% if object.pk %}
      <a class="btn btn-danger" href="{% url 'menu_item_delete_view' object.pk %}" role="button" style="float:right">Delete Menu Item</a>
      {% endif %}
  </form>
  <br>
  <a href={% url 'menu_item_list_view' %}><em>Return to Menu List Without Change</em></a>



  {% else %}
  <h3><em>You don't have permission to view this page.</em></h3>
  <br>
  <a href="javascript:history.go(-1)"><em>Return to Previous Page</em></a>

  {% endif %}

{% endblock %}

templates/app/menu_list.html
{% extends "base.html" %}

{% block content %}
{% if user.profile.position.id = 3 %}
<div class="row">
  <div class="col-md-6"><strong><h3>Menu Items: </h3></strong></div>
  <div class="col-md-6"><a class="btn btn-primary btn-lg" href="{% url 'menu_item_create_view' %}" role="button" style="float:right">Create New Menu Item</a></div>
</div>

<hr>


{% for category in object_list %}
<ul>
  <h4>{{category.category}}</h4>
  {% for item in category.menu_set.all %}
  <ul>
    <div class="media">
      <div class="media-left">
        <a href="{% url 'menu_item_update_view' item.pk %}">
          <img class="media-object" src='{{item.photo_url}}' alt="" width="48" height="48">
        </a>
      </div>
      <div class="media-body">
        <table class='table'>
          <tr>
            <div class="media-body">
            <td><h4 class="media-heading" id='inline'>{{item.item}}</h4></td>
            <td>  <h4 class='media-heading' id='inline' style="float:right">$ {{item.price}}</h4></td>
          </tr>
        </table>
      </div>
    </div>
  </ul>

  {% endfor %}
</ul>


{% endfor %}





{% else %}
<h3><em>You don't have permission to view this page.</em></h3>
{% endif %}
<br>
<a href="javascript:history.go(-1)"><em>Return to Previous Page</em></a>

{% endblock %}

templates/app/order_detail.html
{% extends "base.html" %}
{% block content %}

{% if user.profile.position.id = 2 %}
<table>
  <tr>
    <th>Item</th>
    <th>Quantity</th>
    <th>Notes</th>
  </tr>


{% for object in object_list %}
<tr>
  <td>{{object.item}}</td>
  <td>{{object.quantity}}</td>
  <td>{{object.notes}}</td>

</tr>

{% endfor %}



</table>

{% endif %}

<a href="javascript:history.go(-1)">Back to List</a>


{% endblock %}

templates/app/order_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap %}

{% block content %}
{% if user.profile.position.id = 1 %}

<strong><h4>Create Order: </h4></strong>

  <form class="" action="" method="post" enctype=multipart/form-data>
    {% csrf_token %}


    <table>
           {% for form in inlines %}
               <tr>{{ form|bootstrap }}</tr>
           {% endfor %}
       </table>


    <button type="submit" class="btn btn-primary">Submit Order</button>



  </form>

  {% else %}
  <h3><em>You don't have permission to view this page.</em></h3>
  {% endif %}
  <br>
  <a href="javascript:history.go(-1)"><em>Return to Previous Page</em></a>


{% endblock %}

templates/app/order_list.html
{% extends "base.html" %}
{% block content %}
{% if user.profile.position.id = 1 or user.profile.position.id = 2 %}

<table class='table'>
  <tr>
    <th>Order #</th>
    <th>Server</th>
    <th>Timestamp</th>
    <th style='width:100%; float:right'></th>

  </tr>

{% for object in object_list %}
<tbody>
    <tr>
  <td>Order # {{object.id}}</td>
  <td><em>{{object.server}}</em></td>
  <td><em>{{object.created}}</em></td>
  {% if user.profile.position.id = 2 %}
  {# cook#}
  <td><a type="submit" style='float:right' class="btn btn-primary" href="{% url 'order_update_view' object.pk %}">Order Details</a></td>
  {% endif %}

  {% if user.profile.position.id = 1 %}
  {# server#}
  <td><a type="submit" style='float:right' class="btn btn-primary" href="{% url 'order_update_view' object.pk %}">View Receipt</a></td>
  {% endif %}

    </tr>
  </tbody>
  {% endfor %}

</table>

{% else %}
<h3><em>You don't have permission to view this page.</em></h3>

{% endif %}

<br>
<a href="javascript:history.go(-1)"><em>Return to Previous Page</em></a>

{% endblock %}

templates/app/order_update.html
{% extends "base.html" %}
{% load bootstrap %}
{% load mathfilters %}

{% block content %}
{% if user.profile.position.id = 2 or user.profile.position.id = 1 %}

<h3>Order #  {{order.id}}:</h3>
<hr>

<form class="" action="" method="post">
  {% csrf_token %}
  {% if user.profile.position.id = 2 %}
  {# cook#}
  <input type="checkbox" id="fulfilled" name="fulfilled" value="Fulfilled" style="display:none">
  <button class="btn btn-primary btn-lg" onclick="document.getElementById('fulfilled').checked=!document.getElementById('fulfilled').checked;">Mark as Fulfilled</button>

</form>
<br><br>
<table class='table'>
  <tr>
    <th><h4>Item</h4></th>
    <th><h4>Quantity</h4></th>
    <th><h4>Notes</h4></th>
  </tr>
  <tbody>
    {% for item in items %}
      <tr>
        <td><h4>{{item.item}}</h4></td>
        <td><h4>{{item.quantity}}</h4></td>
        <td><h4>{{item.notes}}</h4></td>
      </tr>
    {% endfor %}
  </tbody>
</table>
  {% endif %}

  {% if user.profile.position.id = 1 %}
  {# server#}
  <input type="checkbox" id="paid" name="paid" value="paid" style="display:none">
  <button class="btn btn-primary btn-lg" onclick="document.getElementById('paid').checked=!document.getElementById('paid').checked;">Mark as Paid</button>

</form>
<br><br>
<table class='table'>
  <tr>
    <th><h4>Item</h4></th>
    <th><h4>Quantity</h4></th>
    <th><h4>Price</h4></th>
    <th><h4>Extended</h4></th>
  </tr>
  <tbody>
    {% for item in items %}
      <tr>
        <td><h4>{{item.item}}</h4></td>
        <td><h4>{{item.quantity}}</h4></td>
        <td><h4>{{item.item.price}}</h4></td>
        <td><h4>{{item.item.price|mul:item.quantity}}</h4></td>

      </tr>
    {% endfor %}
  </tbody>
</table>
<hr>
<div style="float:right"><h4>Subtotal: {{subtotal}}</h4></div><br><br>
<div style="float:right"><h4>Tax: {{tax_total}}</h4></div><br><br>
<div style="float:right"><h4>Grand Total: {{grand_total}}</h4></div><br><br>

{% endif %}
{% else %}
<h3><em>You don't have permission to view this page.</em></h3>
{% endif %}
<a href="javascript:history.go(-1)">Return to Previous Page</a>


{% endblock %}

templates/app/profile_form.html
{% extends "base.html" %}
{% load bootstrap %}
{% block content %}
{% if profile.position == None %}
<form class="" action="" method="post">
  {% csrf_token %}

  {{form|bootstrap}}

  <br>
  <br>
  <button type="submit" class="btn btn-default">Submit Position</button>

</form>
{% else %}

{% if profile.position.id = 3 %}
{# Owner#}
<a class="btn btn-default btn-lg" href="{% url 'menu_item_create_view' %}" role="button">Create Menu Item</a>
<a class="btn btn-default btn-lg" href="{% url 'menu_item_list_view' %}" role="button">List Menu Items</a>
{% endif %}

{% if profile.position.id = 2 %}
{# Cook#}
<a class="btn btn-default btn-lg" href="{% url 'order_list_view' %}" role="button">Pending Orders</a>
{% endif %}

{% if profile.position.id = 1 %}
{# Server#}
<a class="btn btn-default btn-lg" href="{% url 'order_create_view' %}" role="button">Create Order</a>
<a class="btn btn-default btn-lg" href="{% url 'order_list_view' %}" role="button">Unpaid Orders</a>

{% endif %}
{% endif %}

{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Emily's Cafe</title>
    <link rel="stylesheet" href="{% static "app/bootstrap/css/bootstrap.css" %}" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{% static "app/main.css" %}" media="screen" charset="utf-8">
  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          {% if user.is_authenticated %}
          <a class="navbar-brand" href="{% url 'profile_update_view' %}">Emily's Cafe</a>

          {% else %}
          <a class="navbar-brand" href="{% url 'index_view' %}">Emily's Cafe</a>
          {% endif %}
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          {% if request.user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href=""><em>Signed in as {{user}} ({{user.profile.position}})</em></a></li>
            <form class="navbar-form navbar-right" method="POST", action="{% url 'django.contrib.auth.views.logout' %}?next={% url 'index_view' %}">{% csrf_token %}
              <button type="submit" class="btn btn-default">Logout</button>
            </form>
          </ul>

          {% else %}
          <ul class="nav navbar-nav navbar-right">
            <form class="navbar-form navbar-right" method="POST", action="{% url 'django.contrib.auth.views.login' %}">{% csrf_token %}
              <div class="form-group">
                <input type="text" class="form-control" name='username' placeholder="Username">
              </div>
              <div class="form-group">
                <input type="password" class="form-control" name='password' placeholder="Password">
              </div>
              <button type="submit" class="btn btn-default">Login</button>
            </form>
            <li><a href="{% url 'create_user_view' %}">Register</a></li>

          </ul>
          {% endif %}

        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container">

           {% block content %}

           <h1>Hello World</h1>

           {% endblock %}
    </div>

  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
{% if request.user.is_authenticated %}




{% else %}
<br>
<br>

<h1 class=""><em>Welcome!</em></h1><h4 class=""><em>Please sign in or register using links above</em></h4>
{% endif %}

{% endblock %}